import {
  Children,
  isValidElement,
  useState,
  type ComponentPropsWithoutRef,
  type ReactNode,
} from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { normalizeAiMarkdown } from '../utils/normalizeAiMarkdown'

export type MarkdownRenderMode = 'bubble' | 'compact' | 'panel' | 'process' | 'document'

type MarkdownRendererProps = {
  content: string
  className?: string
  mode?: MarkdownRenderMode
}

/**
 * Renders AI-authored Markdown with one controlled React pipeline.
 * Input: raw message text plus an optional wrapper class name.
 * Output: sanitized React nodes that preserve Markdown structure in chat UI.
 */
export function MarkdownRenderer({
  content,
  className = '',
  mode = 'panel',
}: MarkdownRendererProps) {
  const normalizedContent = normalizeAiMarkdown(content, { mode })

  return (
    <div className={`markdown-content markdown-content--${mode} ${className}`.trim()}>
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          a: MarkdownLink,
          pre: props => <MarkdownPre {...props} mode={mode} />,
          table: MarkdownTable,
        }}
      >
        {normalizedContent}
      </ReactMarkdown>
    </div>
  )
}

/**
 * Renders links with safe external navigation defaults for chat content.
 * Input: anchor props generated by react-markdown.
 * Output: a styled anchor element that opens in a new tab.
 */
function MarkdownLink(props: ComponentPropsWithoutRef<'a'>) {
  return <a {...props} target="_blank" rel="noreferrer" />
}

/**
 * Renders block code wrappers with chat-specific layout styles.
 * Input: preformatted block props generated by react-markdown.
 * Output: a styled pre element for fenced or indented code blocks.
 */
function MarkdownPre({
  className,
  children,
  mode,
  ...props
}: ComponentPropsWithoutRef<'pre'> & { mode: MarkdownRenderMode }) {
  const codeBlock = extractCodeBlock(children)

  return (
    <MarkdownCodeShell
      className={className}
      content={codeBlock.content}
      language={codeBlock.language}
      mode={mode}
    >
      <pre className={`markdown-content__code-block ${className ?? ''}`.trim()} {...props}>
        {children}
      </pre>
    </MarkdownCodeShell>
  )
}

/**
 * Wraps wide Markdown tables so they can scroll inside narrow chat bubbles.
 * Input: table props generated by react-markdown.
 * Output: a horizontally scrollable table container.
 */
function MarkdownTable(props: ComponentPropsWithoutRef<'table'>) {
  return (
    <div className="markdown-content__table-scroll">
      <table {...props} />
    </div>
  )
}

type MarkdownCodeShellProps = {
  children: ReactNode
  className?: string
  content: string
  language?: string
  mode: MarkdownRenderMode
}

type MarkdownCodeElementProps = {
  className?: string
  children?: ReactNode
}

/**
 * Wraps code blocks with a lightweight toolbar for language and copy actions.
 * Input: rendered pre element, extracted code text, language label, and render mode.
 * Output: a styled code shell around the preformatted block.
 */
function MarkdownCodeShell({
  children,
  className,
  content,
  language,
  mode,
}: MarkdownCodeShellProps) {
  const [copied, setCopied] = useState(false)

  async function handleCopy() {
    if (!content.trim() || !navigator.clipboard?.writeText) {
      return
    }

    try {
      await navigator.clipboard.writeText(content)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 1200)
    } catch {
      // Ignore clipboard errors in unsupported or restricted contexts.
    }
  }

  return (
    <div className={`markdown-content__code-shell markdown-content__code-shell--${mode} ${className ?? ''}`.trim()}>
      <div className="markdown-content__code-toolbar">
        <span>{language ?? 'code'}</span>
        <button
          className="markdown-content__code-copy"
          type="button"
          onClick={() => void handleCopy()}
          disabled={!content.trim()}
        >
          {copied ? 'Copied' : 'Copy'}
        </button>
      </div>
      {children}
    </div>
  )
}

type ExtractedCodeBlock = {
  content: string
  language?: string
}

/**
 * Extracts plain text and the language token from a rendered Markdown code block.
 * Input: pre children generated by react-markdown.
 * Output: normalized code text plus an optional language label.
 */
function extractCodeBlock(children: ReactNode): ExtractedCodeBlock {
  const codeChild = Children.toArray(children).find(
    child => isValidElement<MarkdownCodeElementProps>(child) && child.type === 'code',
  )

  if (!codeChild || !isValidElement<MarkdownCodeElementProps>(codeChild)) {
    return {
      content: stringifyReactNode(children).replace(/\n$/, ''),
    }
  }

  const className = typeof codeChild.props.className === 'string' ? codeChild.props.className : ''
  const languageMatch = /language-([\w-]+)/.exec(className)

  return {
    content: stringifyReactNode(codeChild.props.children).replace(/\n$/, ''),
    language: languageMatch?.[1],
  }
}

/**
 * Flattens nested React nodes into a plain string for copy and preview helpers.
 * Input: arbitrary React children.
 * Output: stringified text content.
 */
function stringifyReactNode(node: ReactNode): string {
  if (typeof node === 'string' || typeof node === 'number') {
    return String(node)
  }

  if (Array.isArray(node)) {
    return node.map(item => stringifyReactNode(item)).join('')
  }

  if (isValidElement<{ children?: ReactNode }>(node)) {
    return stringifyReactNode(node.props.children)
  }

  return ''
}
