import type { ComponentPropsWithoutRef } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { normalizeAiMarkdown } from '../utils/normalizeAiMarkdown'

type MarkdownRendererProps = {
  content: string
  className?: string
}

/**
 * Renders AI-authored Markdown with one controlled React pipeline.
 * Input: raw message text plus an optional wrapper class name.
 * Output: sanitized React nodes that preserve Markdown structure in chat UI.
 */
export function MarkdownRenderer({ content, className = '' }: MarkdownRendererProps) {
  const normalizedContent = normalizeAiMarkdown(content)

  return (
    <div className={`markdown-content ${className}`.trim()}>
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          a: MarkdownLink,
          pre: MarkdownPre,
          table: MarkdownTable,
        }}
      >
        {normalizedContent}
      </ReactMarkdown>
    </div>
  )
}

/**
 * Renders links with safe external navigation defaults for chat content.
 * Input: anchor props generated by react-markdown.
 * Output: a styled anchor element that opens in a new tab.
 */
function MarkdownLink(props: ComponentPropsWithoutRef<'a'>) {
  return <a {...props} target="_blank" rel="noreferrer" />
}

/**
 * Renders block code wrappers with chat-specific layout styles.
 * Input: preformatted block props generated by react-markdown.
 * Output: a styled pre element for fenced or indented code blocks.
 */
function MarkdownPre({ className, ...props }: ComponentPropsWithoutRef<'pre'>) {
  return <pre className={`markdown-content__code-block ${className ?? ''}`.trim()} {...props} />
}

/**
 * Wraps wide Markdown tables so they can scroll inside narrow chat bubbles.
 * Input: table props generated by react-markdown.
 * Output: a horizontally scrollable table container.
 */
function MarkdownTable(props: ComponentPropsWithoutRef<'table'>) {
  return (
    <div className="markdown-content__table-scroll">
      <table {...props} />
    </div>
  )
}
